# S3 Media Bucket Configuration
knp_gaufrette:
    adapters:
        s3_attachments:
            aws_s3:
                service_id: 'aligent_s3.client'
                bucket_name: '%amazon_s3.bucket_name%'
                options:
                    directory:  'attachment'
                    create: true

        s3_public_mediacache:
            aws_s3:
                service_id: 'aligent_s3.client'
                bucket_name: '%amazon_s3.bucket_name%'
                options:
                    directory:  'media/cache'
                    create: true


        s3_protected_mediacache:
            aws_s3:
                service_id: 'aligent_s3.client'
                bucket_name: '%amazon_s3.bucket_name%'
                options:
                    directory:  'protected_mediacache'
                    create: true
    filesystems:
        attachments:
            adapter: s3_attachments
        public_mediacache:
            adapter: s3_public_mediacache
        protected_mediacache:
            adapter: s3_protected_mediacache
